name: Deploy Website to EC2

# Triggers the workflow on pushes to the 'main' branch or manually
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # This action handles the secure connection and file transfer
      - name: Deploy files to EC2 via SSH/rsync
        uses: easingthemes/ssh-deploy@main
        with:
          # This is the correct IP for your running server
          HOST: '3.23.105.70' 
          
          # The default user for Amazon Linux is ec2-user
          USERNAME: 'ec2-user'
          
          # Reference the Private Key you stored as a secret (which we fixed)
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # Source is the root of your GitHub repository
          SOURCE: './'
          
          # Target is the Apache web server directory on the EC2 instance
          TARGET: '/var/www/html/'
          
          # Use rsync arguments for efficient transfer
          ARGS: '-avz --delete'
